# Generated by Django 3.0.8 on 2020-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20200706_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='results',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
