# Generated by Django 3.0.8 on 2020-07-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20200728_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nature_complaints', to='complaints.Nature'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_complaints', to='complaints.Location'),
        ),
    ]
