# Generated by Django 3.0.8 on 2020-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20200728_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-open_date']},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Created', 'Created'), ('Created', 'Created')], max_length=20),
        ),
    ]
