# Generated by Django 3.0.8 on 2020-07-29 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_auto_20200729_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
