# Generated by Django 3.0.8 on 2020-08-05 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0011_auto_20200805_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='feedback_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
