# Generated by Django 3.0.8 on 2020-08-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_auto_20200805_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='attachments')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='complaints.Complaint')),
            ],
        ),
    ]
