# Generated by Django 3.0.8 on 2020-08-07 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0013_auto_20200805_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=500)),
                ('feedback_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='feedback_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='feedback_by',
        ),
        migrations.CreateModel(
            name='FeedbackDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('file', models.FileField(upload_to='feedback_docs')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docs', to='complaints.Feedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='complaints.Complaint'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
