# Generated by Django 3.0.8 on 2020-08-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_remove_feedbackdocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackdocument',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='complaints.Feedback'),
        ),
    ]
